kind: pipeline
name: test

workspace:
  base: /go
  path: src/github.com/davidbyttow/mono-drone

steps:
- name: test
  image: golang
  commands:
  - go get ./...
  - go test ./...
  when:
    event:
    - push
    - pull_request

---
kind: pipeline
name: apple

workspace:
  base: /go
  path: src/github.com/davidbyttow/mono-drone

steps:
- name: build
  image: golang
  commands:
  - go build -o apple ./cmd/apple
  when:
    event:
    - push
    - pull_request

depends_on:
- test

---
kind: pipeline
name: banana

workspace:
  base: /go
  path: src/github.com/davidbyttow/mono-drone

steps:
- name: build
  image: golang
  commands:
  - go build -o banana ./cmd/banana
  when:
    event:
    - push
    - pull_request

depends_on:
- test
